# Generated by Django 3.1.3 on 2020-11-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titel',
            new_name='title',
        ),
    ]
