# Generated by Django 3.1.3 on 2020-11-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='inage',
            new_name='image',
        ),
    ]
